url: https://githome.io
baseurl: "/knowledge-base" # It's the default

name: 知识库
name_en: Knowledge Base
title: 知识库 - Knowledge Base
keywords: "计算机科学，CS，知识库，知识体系"
description: "计算机知识库"

markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false # syntax highlighter 和 highlight.js 不应该同时引用
  toc_levels: 2..3

# Building settings
permalink: pretty

include: ["_assets", ".images"]

exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - vendor

plugins:
  - jekyll-sitemap

sass:
  sass_dir: _scss
  style: :compressed

#===================== more settings =====================#

repourl: https://github.com/jinsyin/knowledge-base
copyright: Powered by Jinsyin

# Site Language
# "zh-cmn-Hans" => 简体中文; "zh-cmn-Hant" => 繁体中文; "en" => English
lang: "zh-cmn-Hans"

author:
  name: Jinsyin
  github: https://github.com/jinsyin
